package com.example.buildsrc

object Versions {
    const val gson = "2.10.1"
    const val hiltAndroid = "2.47"
    const val hiltWork = "1.0.0"
    const val hiltCompiler = "1.0.0"
    const val hiltNavigationCompose = "1.0.0"
    const val okHttp = "4.11.0"
    const val retrofit = "2.9.0"
    const val stetho = "1.6.0"
    const val arch = "2.6.1"
    const val arrow = "1.2.0"
    const val mockitoKotlin = "5.0.0"
    const val androidxCore = "1.10.1"
    const val trace = "1.1.0"
    const val activityCompose = "1.7.2"
    const val composeBom = "2023.06.01"
    const val coil = "2.4.0"
    const val workRuntime = "2.8.1"
    const val lifecycleRuntimeCompose = "2.6.1"
    const val navigationCompose = "2.6.0"
    const val junit = "4.13.2"
    const val junitEx = "1.1.5"
    const val espresso = "3.5.1"
    const val material = "1.9.0"
}